name: QA Playwright Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install browser dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libatspi2.0-0 \
            libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libasound2t64

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

          # Add Docker’s official GPG key
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

          # Setup stable repository
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update

          # Install Docker Engine and Docker Compose plugin
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

          # Check versions
          docker --version
          docker compose version

      - name: Start docker-compose services
        run: docker compose up -d

      - name: Wait for frontend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Frontend is up!"
              break
            else
              echo "Waiting for frontend..."
              sleep 5
            fi
          done

      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest-playwright pytest-html
          playwright install

      - name: Run Playwright tests with HTML report
        run: |
          pytest tests/ --html=report.html --self-contained-html

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: report.html
